### ISSUE TITLE
A question about etymology

### ISSUE THREAD

**Issue by Pharap** [TheTechnobear/Orac#11]
I just stumbled upon this because someone I was watching starred it.
May I ask, is the project's name 'Orac' anything to do with [the Orac computer](https://en.wikipedia.org/wiki/Orac_(Blake%27s_7)) from [Blake's 7](https://en.wikipedia.org/wiki/Blake's_7) by any chance?

**Comment by TheTechnobear** [comment]
Yes :) 
So orac started on the organelle , so I was think of names around variations on organelle modular rack, so O-rack , 
BUT as it was going to be cross platform, I didn’t want to tie the name too closely to the organelle - so yeah Orac fitted nicely - as it’s known  outside the Organelle - and a hidden connection to something is always fun :)
