### ISSUE TITLE
$-help.pd file

### ISSUE THREAD

**Issue by JamessStick** [TheTechnobear/Orac#16]
Hi @TheTechnobear 

I started to use yours mutable instrument's pure data patches, but I realised that rngs, r chorus, r reverb or r ensemble patches haven't the help patch, who is very useful for me to understand how to use them.

Is there any specific reason?

I'm using the macOS version on Mojave. 

Thanks

**Comment by TheTechnobear** [comment]
yes, Ive not had time to create them  - you can look at the the orac module to see what messages these respond to.
e.g. 
https://github.com/TheTechnobear/Orac/blob/master/Core/orac/modules/synth/rngs/module.pd

but this is open source, if you wish to create a help patch, and submit a pull request that would be wonderful.

btw: I should also mention on the readme, I do not really support macos for mi4pd or orac, 
this is for developement purposes only.


I know this is not perfect, but please understand i do alot of work on a variety of open source project, 
I do this in my own free time, and then give away for free.
so there is only so much i can commit to.

Thanks
Mark

**Comment by JamessStick** [comment]
Hi Mark,

thanks for your reply. I know you did the patches for macOS only for development and all this work is open source. It's very great and priceless.

About the rings object I just wanted to understand it and its arguments. Finally I found a different rings objects on your profil who show me  which arguments I can send to it. The first I saw was just empty. 

I'm actually making a ready-to-go patch with knob controls for every objects, which includes polyphonic versions of lmnts and brds. I will send you when I'll finish them if you are interested in. By the way I have a buffer problem. In fact I can't open two time the same object (lmnts for example) even in two different pure data's patches cause I get clock problems. Do you have any idea why it happens and if is possible to solve this?

Thanks you,

Gino
