### ISSUE TITLE
is is possible for modules.json to use a relaxed json parser

### ISSUE THREAD

**Issue by dr-kd** [TheTechnobear/Orac#18]
We all know that the json spec makes comments illegal.  However json parsers that allow this do exist - and comments make sense in json for configuration files - which modules.json is.

Is it possible to get the puredata json parser or whatever it is to be relaxed so modules.json can contain comments?

**Comment by TheTechnobear** [comment]
I use the cJson library for parsing , if/when this supports comments , then Orac will too ;)
