### ISSUE TITLE
Orac 2.0 - Multiple MIDI channels not fully working in parallel setup

### ISSUE THREAD

**Issue by artaction** [TheTechnobear/Orac#4]
Steps to reproduce:
- Install Orac 2.0
- Go to Organelle OS and set up global midi settings (I'm using MIDI CH16 in, No MIDI Output)... changing these settings doesn't seem to effect much as long as your controller is showing up and you save the global midi settings. (I'm using an OP-Z as midi controller plugged into the USB input of the organelle)
- change from serial to parallel in orac
- load a synth on A1, B1, C1 for a quick sound source to test each midi channel
- change A MIDI input to Channel 5, B MIDI input to Channel 6, B MIDI input to Channel 8
- play some notes on your controller

Results:
A + MIDI channel 5 = works ok. Notes play from controller over channel 5
B + MIDI channel 6 = Works ok. Notes play from controller over channel 6
C + MIDI channel 8 = midi notes do not play from the controller. 
The MIDI channel that I choose doesn't seem to make a difference, it appears to be a problem with C. 

Other notes:
The OP-Z is playing a sequence of notes on each of midi channels 1-8. 

If I select the synth module that is on C1 and play a sequence from my controller, it plays notes from MIDI channel 1. This is odd because on the Organelle, MIDI channel 1 hasn't been mapped out to anything through either the global OS or on Orac 2. 

Additionally, if I select the synth on module A1 or B1 and play the sequence, these also are picking up notes from MIDI channel 1 when they are selected and active in Orac. 

I was able to get multi-channel midi inputs working in Orac 1, so I don't think the source of the issue is the OP-Z hardware or the Organelle global midi settings getting in the way of things.

**Comment by TheTechnobear** [comment]
The global midi setting on OrganelleOS has no effect 

The active input midi channel is controlled on the router module under ‘main ctrl’ 

I’ve been doing exactly this for the new demo patch (demo2) which will be in beta 2 today.  
But I can say for sure it works fine on beta 1 too , if setup correctly. 

Anyway check with beta 2 released today as shown on the video. 
( so initially as per video , ie ch 1 -3 for chains)
