### ISSUE TITLE
The version of OSC control on Patchstorage resets values on page event.

### ISSUE THREAD

**Issue by jaggednz** [TheTechnobear/Orac#8]
The version supplied from Github behaves correctly, but I only found it because I've been poking around ORAC and MEC.

Using control patch from https://patchstorage.com/orac-remote-control-patches/
Running ORAC 2.0 (latest deb) on PatchBox, paging between modules resets all values for the module.
I was able to fix by modifying ctrl.pd but was quite confusing until I modified the patch to output all the OSC messages to debug.

edit: Maybe also mention OscClients in the main readme.md ?

**Comment by TheTechnobear** [comment]
Yeah, this is a version mismatch - they work with a version of mec that’s not released yet - I’ll put back the 1.0 versions for now, until new mec is released.
